<h1 class="hww-faq-title"><?php echo $this->getFaqTitle(); ?></h1>

<?php $faqItems = $block->getFaqItems(); ?>
<?php $faqCategories = $block->getFaqCategories(); ?>

<div id="search-container" class="search-bar">
    <input type="text" id="search-bar" class="search-text" placeholder="Search for..." />
    <button type="button" id="search-button" class="search-button" value="Search">Search</button>
</div>

<?php if ($this->isSidebarEnabled()) : ?>
    <div class="hww-faq-categories">
        <h2 class="hww-faq-category-title">Categories</h2>
        <ul class="hww-faq-category-list">
            <li class="hww-faq-category-item">
                <a href="#" class="category-link hww-faq-show-all" data-category-id="show-all">
                    Show All
                </a>
            </li>
            <?php foreach ($faqCategories as $category) : ?>
                <li class="hww-faq-category-item">
                    <a href="#" class="category-link hww-faq-category-link" data-category-id="<?php echo $category->getCategoryId(); ?>">
                        <?php echo $category->getCategoryName(); ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
<div class="hww-faq-all-category-sections">
    <?php foreach ($faqCategories as $category) : ?>
        <?php
        $categoryItems = array_filter($faqItems, function ($faqItem) use ($category) {
            return $faqItem->getCategoryId() == $category->getCategoryId() && $faqItem->getAnswer();
        });
        ?>

        <?php if (!empty($categoryItems)) : ?>
            <div class="category-section hww-faq-category-section" id="category-<?php echo $category->getCategoryId(); ?>">
                <h2 class="hww-faq-category-name"><?php echo $category->getCategoryName(); ?></h2>

                <ul class="hww-faq-item-list">
                    <?php $count = 1; ?>
                    <?php foreach ($categoryItems as $faqItem) : ?>
                        <?php if ($faqItem->getCategoryId() == $category->getCategoryId() && $faqItem->getAnswer()) : ?>
                            <li id="faq-item" class="faq-item hww-faq-item">
                                <strong class="hww-faq-question">Q<?php echo $count; ?>: <?php echo $faqItem->getQuestion(); ?></strong><br>
                                <span class="hww-faq-answer">A: <?php echo $faqItem->getAnswer(); ?></span>
                            </li>
                            <?php $count++; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>


<!-- Section to Ask a Question -->
<?php if ($this->isAskQuestionEnabled()) : ?>
    <div class="hww-faq-ask-question-section">
        <h2 class="hww-faq-ask-question-title">Ask a Question</h2>
        <form action="<?php echo $block->getUrl('faq/index/submitQuestion') ?>" method="post" id="ask-question-form" class="hww-faq-form">
            <label for="category" class="hww-faq-label">Select Category:</label>
            <select name="category" id="category" required class="hww-faq-select">
                <option value="" selected disabled>Select a category</option>
                <?php foreach ($faqCategories as $category) : ?>
                    <option value="<?php echo $category->getCategoryId(); ?>" class="hww-faq-option"><?php echo $category->getCategoryName(); ?></option>
                <?php endforeach; ?>
            </select>
            <br>
            <label for="question" class="hww-faq-label">Your Question:</label>
            <textarea name="question" id="question" cols="30" rows="5" required class="hww-faq-textarea"></textarea>
            <br>
            <input type="submit" value="Submit Question" class="hww-faq-submit-button">
        </form>
    </div>
<?php endif; ?>


<script>
    require(['jquery', 'jquery/ui'], function ($) {
        $(document).ready(function () {
            // Hide all answers initially
            $('.hww-faq-answer').hide();

            // Show the selected category section on category link click
            $('.category-link').on('click', function (event) {
                event.preventDefault();

                $(".faq-item").show();
                $(".faq-item").removeClass("active")
                $(".hww-faq-category-name").show();
                $('.hww-faq-answer').hide();

                var categoryId = $(this).data('category-id');

                if (categoryId === 'show-all') {
                    // Show all category sections
                    $('.category-section').show();
                } else {
                    // Hide all other category sections
                    $('.category-section').hide();

                    // Show the selected category section
                    $('#category-' + categoryId).show();
                }
            });

            // Toggle answer visibility on question click
            $(".faq-item").on("click", function () {
                $(this).find(".hww-faq-answer").slideToggle(500);
                $(this).toggleClass("active");

            });

            // Function to handle search
            $("#search-button").click(function () {
                var searchTerm = $("#search-bar").val().toLowerCase();

                // Hide all FAQ items, answers, and corresponding category names
                $(".faq-item").hide();
                $(".hww-faq-category-name").hide();
                $('.hww-faq-answer').hide();

                // Iterate through each FAQ item and show if it matches the search term
                $(".faq-item").filter(function () {
                    var questionText = $(this).find(".hww-faq-question").text().toLowerCase();
                    var answerText = $(this).find(".hww-faq-answer").text().toLowerCase();

                    // Check if the search term is present in the question or answer
                    var isMatch = questionText.includes(searchTerm) || answerText.includes(searchTerm);

                    // Show the corresponding category name and answer if there is a match
                    if (isMatch) {
                        var categoryId = $(this).closest(".hww-faq-category-section").attr("id").replace("category-", "");
                        $("#category-" + categoryId + " .hww-faq-category-name").show();
                        $(this).find(".hww-faq-answer").show();
                    }
                    return isMatch;
                }).show();

                // Highlight the keyword in the displayed FAQ items
                $(".faq-item:visible").each(function () {
                    var questionText = $(this).find(".hww-faq-question").text();
                    var answerText = $(this).find(".hww-faq-answer").text();

                    // Highlight the keyword in the question and answer
                    questionText = questionText.replace(new RegExp(searchTerm, "gi"), function (match) {
                        return "<span class='highlight'>" + match + "</span>";
                    });
                    answerText = answerText.replace(new RegExp(searchTerm, "gi"), function (match) {
                        return "<span class='highlight'>" + match + "</span>";
                    });

                    // Update the HTML with the highlighted text
                    $(this).find(".hww-faq-question").html(questionText);
                    $(this).find(".hww-faq-answer").html("A: " + answerText);
                });
            });
        });
    });
</script>

<style>
    .highlight {
        background-color: yellow;
    }
</style>